plugins {
    id("com.stax.android.application")
    id("com.stax.compose")
    id("com.stax.koin")
    id("com.stax.testing")
}

dependencies {
    implementation(libs.androidx.startup.runtime)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.navigation3.runtime)
    implementation(libs.androidx.navigation3.ui)
    implementation(libs.androidx.lifecycle.viewmodel.navigation3)
    implementation(project(":core:domain"))
    implementation(project(":core:database"))
    implementation(project(":core:data"))
    implementation(project(":core:presentation"))
    implementation(project(":core:design-system"))
    implementation(project(":feature:onboarding:presentation"))
    implementation(project(":feature:compounds:presentation"))
    implementation(project(":feature:protocols:presentation"))
    implementation(project(":feature:sites:presentation"))
    implementation(project(":feature:dashboard:presentation"))
    implementation(project(":feature:reconstitution:presentation"))
    implementation(project(":feature:logging:presentation"))
    implementation(project(":feature:settings:presentation"))
    implementation(project(":widget"))
    implementation(project(":shortcut"))
    implementation(project(":work"))
    implementation(project(":notification"))
}
