#!/usr/bin/env python3
"""
sync-issues.py — regenerate GitHub issue titles + bodies from ISSUES.md.

ISSUES.md is the single source of truth. Each `### Mx-yy · Title` section maps to
the GitHub issue whose title starts with the same `Mx-yy` id. This script rewrites
each issue's title (from the heading) and body (from the section), so editing
ISSUES.md / detailed-spec.md and re-running is the only step needed — no hand-editing
issues, ever.

Why this exists: issue bodies used to embed `#L<line>` anchors (drift on every edit)
plus a *copy* of the section (must be re-synced manually). Both rot. The stable key
is the `Mx-yy` id — it prefixes every title and every `### ` heading and survives
line moves *and* title edits. Bodies now point with `search "### Mx-yy"`, not line
numbers.

Usage:
  python3 scripts/sync-issues.py --dry-run        # preview changes, edit nothing
  python3 scripts/sync-issues.py                  # apply to OPEN issues
  python3 scripts/sync-issues.py --only M5-04,M5-05
  python3 scripts/sync-issues.py --include-closed # also rewrite closed issues
                                                  # (WARNING: wipes manual notes on them)

Requires: gh (authenticated), python3. Compatible with start-oldest-feature.sh
(the blob prefix is still present, so its prefix-strip yields relative paths).
"""
import argparse
import json
import re
import subprocess
import sys

BRANCH = "dev"
ISSUES_FILE = "ISSUES.md"
SPEC_FILE = "detailed-spec.md"

ID_RE = re.compile(r"(M\d+-\d+[a-z]*|X-\d+)")
HEADING_RE = re.compile(r"^###\s+(M\d+-\d+[a-z]*|X-\d+)\s*·\s*(.*?)\s*$")


def sh(*args):
    return subprocess.run(args, capture_output=True, text=True)


def repo_slug():
    r = sh("gh", "repo", "view", "--json", "nameWithOwner", "-q", ".nameWithOwner")
    if r.returncode != 0:
        sys.exit(f"gh repo view failed: {r.stderr.strip()}")
    return r.stdout.strip()


def parse_sections(text):
    """Return (ordered_ids, {id: (title, body_lines)}) from ISSUES.md."""
    lines = text.splitlines()
    sections = {}
    ordered = []
    cur_id = None
    cur_title = None
    buf = []

    def flush():
        if cur_id is not None:
            # trim trailing blanks / milestone separators
            b = buf[:]
            while b and (b[-1].strip() == "" or b[-1].strip() == "---"):
                b.pop()
            sections[cur_id] = (cur_title, b)

    for ln in lines:
        m = HEADING_RE.match(ln)
        if m:
            flush()
            cur_id, cur_title = m.group(1), m.group(2)
            ordered.append(cur_id)
            buf = []
            continue
        if ln.startswith("## ") and cur_id is not None:
            # next milestone header ends the current section
            flush()
            cur_id = cur_title = None
            buf = []
            continue
        if cur_id is not None:
            buf.append(ln)
    flush()
    return ordered, sections


def gh_issues(include_closed):
    state = "all" if include_closed else "open"
    r = sh("gh", "issue", "list", "--state", state, "--limit", "500",
           "--json", "number,title,body,state")
    if r.returncode != 0:
        sys.exit(f"gh issue list failed: {r.stderr.strip()}")
    out = {}
    for it in json.loads(r.stdout):
        m = ID_RE.match(it["title"])
        if m:
            out[m.group(1)] = it
    return out


def fmt_dep(mid, id2num):
    n = id2num.get(mid)
    return f"#{n} ({mid})" if n else mid


def render_deps(dep_text, id2num, ordered):
    dep_text = dep_text.strip().rstrip(".")
    if dep_text.lower() == "none" or not dep_text:
        return "none"
    out = []
    for part in [p.strip() for p in dep_text.split(",") if p.strip()]:
        ids = ID_RE.findall(part)
        if ".." in part and len(ids) == 2 and ids[0] in ordered and ids[1] in ordered:
            i, j = sorted([ordered.index(ids[0]), ordered.index(ids[1])])
            out += [fmt_dep(m, id2num) for m in ordered[i:j + 1]]
        elif ids:
            out += [fmt_dep(m, id2num) for m in ids]
        else:
            out.append(part)
    return ", ".join(out)


def build_body(mid, body_lines, id2num, ordered, blob):
    # rewrite only the Depends-on bullet; copy the rest verbatim
    rebuilt = []
    for ln in body_lines:
        dm = re.match(r"^- \*\*Depends on\*\*:\s*(.*)$", ln)
        if dm:
            rebuilt.append(f"- **Depends on**: {render_deps(dm.group(1), id2num, ordered)}.")
        else:
            rebuilt.append(ln)
    section = "\n".join(rebuilt).strip("\n")
    header = (
        f"Issue ID: `{mid}`\n"
        f"Source of truth: [`{ISSUES_FILE}`]({blob}/{ISSUES_FILE}) "
        f"(search `### {mid}`) and [`{SPEC_FILE}`]({blob}/{SPEC_FILE}) "
        f"(read the §refs below). Generated by `scripts/sync-issues.py` — "
        f"edit the docs and re-run; do not hand-edit issues.\n"
        f"\n---\n\n"
    )
    return header + section + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--include-closed", action="store_true")
    ap.add_argument("--only", default="", help="comma-separated Mx-yy ids")
    args = ap.parse_args()

    blob = f"https://github.com/{repo_slug()}/blob/{BRANCH}"
    with open(ISSUES_FILE, encoding="utf-8") as f:
        ordered, sections = parse_sections(f.read())
    # Resolve dependency links (#NN) against ALL issues — closed deps must still link.
    all_issues = gh_issues(include_closed=True)
    id2num = {mid: it["number"] for mid, it in all_issues.items()}
    only = {s.strip() for s in args.only.split(",") if s.strip()}

    changed = unchanged = missing = skipped_closed = 0
    for mid in ordered:
        if only and mid not in only:
            continue
        it = all_issues.get(mid)
        if it is None:
            missing += 1
            print(f"·· {mid}: no issue — skip")
            continue
        if not args.include_closed and it.get("state") != "OPEN":
            skipped_closed += 1  # closed: still link-resolvable, but don't rewrite history
            continue
        title, body_lines = sections[mid]
        new_title = f"{mid} · {title}"
        new_body = build_body(mid, body_lines, id2num, ordered, blob)
        n = it["number"]
        # normalize CRLF / trailing ws for comparison
        cur_body = it["body"].replace("\r\n", "\n").rstrip() + "\n"
        if it["title"] == new_title and cur_body == new_body:
            unchanged += 1
            continue
        changed += 1
        diff_t = "" if it["title"] == new_title else f"  TITLE: {it['title']!r} -> {new_title!r}"
        print(f">> #{n} {mid}{diff_t}")
        if not args.dry_run:
            import tempfile, os
            fd, path = tempfile.mkstemp(suffix=".md")
            os.write(fd, new_body.encode())
            os.close(fd)
            r = sh("gh", "issue", "edit", str(n), "--title", new_title, "--body-file", path)
            os.unlink(path)
            if r.returncode != 0:
                print(f"   !! edit failed: {r.stderr.strip()}")

    print(f"\n{'DRY-RUN ' if args.dry_run else ''}done: "
          f"{changed} changed, {unchanged} unchanged, "
          f"{skipped_closed} closed-skipped, {missing} missing.")


if __name__ == "__main__":
    main()
